const Header = document.createElement("div");
Header.className = "header";
let body = document.querySelector("body");
body.appendChild(Header);
let h1 = document.createElement("h1");
h1.innerHTML = "Welcome To The Book Store";
h1.className = "h1";
Header.appendChild(h1);
let div1 = document.createElement("div");
div1.className = "div1";
body.appendChild(div1);
let button1 = document.createElement("button");
button1.innerHTML = `<i class="fa-solid fa-arrow-down fa-xl"></i>`;
button1.className = "button1";
div1.appendChild(button1);
let buttoncart = document.createElement("button");
buttoncart.innerHTML = `<i class="fa-solid fa-shopping-cart fa-xl"></i>`;
buttoncart.className = "buttoncart";
buttoncart.id="cartbutton";
body.appendChild(buttoncart);
let heading1 = document.createElement("h1");
heading1.innerHTML = "Book Catalog";
heading1.className = "h1";
heading1.id = "heading1";
body.appendChild(heading1);
let div2 = document.createElement("div");
div2.className = "div2";
body.appendChild(div2);